language: java
script: mvn integration-test -Dmaven.javadoc.skip=true --settings=.settings.xml
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V --settings=.settings.xml

jdk:
  - oraclejdk8
